version 0.52

diff --git a/SMLUnit/Makefile.in b/SMLUnit/Makefile.in
--- a/SMLUnit/Makefile.in
+++ b/SMLUnit/Makefile.in
@@ -5,7 +5,7 @@
 # If you'd like to install this module individually, just copy LIBFILES to
 # your favorite place by your hand.
 
-srcdir = @SMLUNITDIR@
+srcdir = @srcdir_smlunit@
 builddir = @builddir@
 top_srcdir = @top_srcdir@
 top_builddir = @top_builddir@
@@ -33,5 +33,17 @@ install:
 	    || exit $$?; \
 	   done); \
 	echo "use \"`$(MKSMLPATH) -sh $(libdir_smlunit)/smlunitlib.sml`\";" > '$(DESTDIR)$(libdir_smlsharp)/smlunitlib.sml'
+
+doc:
+	-$(MAKE) smldoc
+
+smldoc: 
+	@if test 'x$(SMLDOC)' = 'x'; then \
+	  echo '*** smldoc not found.'; exit 1; \
+	fi
+	-rm -rf ./doc/api
+	mkdir -p ./doc/api
+	# overwrite --directory option specified in smldoc.cfg.
+	$(SMLDOC) -a $(srcdir)/src/smldoc.cfg --directory=./doc/api
 
 # Makefile.in ends here.
